const enum_script = @import("enums.zig");
const constant_script = @import("language_constants.zig");
const TokenType = enum_script.TokenType;

const TokenPair = struct {
    lexem: []const u8,
    TokenType: TokenType,
};

pub const TokenPairs = [_]TokenPair{
    TokenPair{ .lexem = constant_script.FUNC, .TokenType = TokenType.Func },
    TokenPair{ .lexem = constant_script.IF, .TokenType = TokenType.If },
    TokenPair{ .lexem = constant_script.ELSE, .TokenType = TokenType.Else },
    TokenPair{ .lexem = constant_script.FOR, .TokenType = TokenType.For },
    TokenPair{ .lexem = constant_script.WHILE, .TokenType = TokenType.While },
    TokenPair{ .lexem = constant_script.RETURN, .TokenType = TokenType.Return },
    TokenPair{ .lexem = constant_script.BREAK, .TokenType = TokenType.Break },
    TokenPair{ .lexem = constant_script.CONTNUE, .TokenType = TokenType.Continue },
    TokenPair{ .lexem = constant_script.PRINT, .TokenType = TokenType.Print },
    TokenPair{ .lexem = constant_script.PRINTLN, .TokenType = TokenType.Println },
    TokenPair{ .lexem = constant_script.TRUE, .TokenType = TokenType.True },
    TokenPair{ .lexem = constant_script.FALSE, .TokenType = TokenType.False },
    TokenPair{ .lexem = constant_script.IN, .TokenType = TokenType.In },
    TokenPair{ .lexem = constant_script.NEW, .TokenType = TokenType.New },
    TokenPair{ .lexem = constant_script.DEFER, .TokenType = TokenType.Defer },
    TokenPair{ .lexem = constant_script.DELETE, .TokenType = TokenType.Delete },

    TokenPair{ .lexem = constant_script.I8, .TokenType = TokenType.i8 },
    TokenPair{ .lexem = constant_script.U8, .TokenType = TokenType.u8 },
    TokenPair{ .lexem = constant_script.I32, .TokenType = TokenType.i32 },
    TokenPair{ .lexem = constant_script.U32, .TokenType = TokenType.u32 },
    TokenPair{ .lexem = constant_script.I64, .TokenType = TokenType.i64 },
    TokenPair{ .lexem = constant_script.U64, .TokenType = TokenType.u64 },
    TokenPair{ .lexem = constant_script.F32, .TokenType = TokenType.f32 },
    TokenPair{ .lexem = constant_script.F64, .TokenType = TokenType.f64 },
    TokenPair{ .lexem = constant_script.STRING, .TokenType = TokenType.String },
    TokenPair{ .lexem = constant_script.BOOL, .TokenType = TokenType.Bool },
    TokenPair{ .lexem = constant_script.CHAR, .TokenType = TokenType.Char },
    TokenPair{ .lexem = constant_script.VOID, .TokenType = TokenType.Void },
    TokenPair{ .lexem = constant_script.CONST, .TokenType = TokenType.Const },
    TokenPair{ .lexem = constant_script.INT, .TokenType = TokenType.Int },
    TokenPair{ .lexem = constant_script.USIZE, .TokenType = TokenType.Usize },

    TokenPair{ .lexem = constant_script.PLUS, .TokenType = TokenType.Plus },
    TokenPair{ .lexem = constant_script.PLUS_PLUS, .TokenType = TokenType.PlusPlus },
    TokenPair{ .lexem = constant_script.MINUS, .TokenType = TokenType.Minus },
    TokenPair{ .lexem = constant_script.MULTIPLY, .TokenType = TokenType.Multiply },
    TokenPair{ .lexem = constant_script.DIVIDE, .TokenType = TokenType.Divide },
    TokenPair{ .lexem = constant_script.EQUALS, .TokenType = TokenType.Equals },
    TokenPair{ .lexem = constant_script.PLUS_EQUALS, .TokenType = TokenType.PlusEquals },
    TokenPair{ .lexem = constant_script.MINUS_EQUALS, .TokenType = TokenType.MinusEquals },
    TokenPair{ .lexem = constant_script.MULTIPLY_EQUALS, .TokenType = TokenType.MultiplyEquals },
    TokenPair{ .lexem = constant_script.DIVIDE_EQUALS, .TokenType = TokenType.DivideEquals },
    TokenPair{ .lexem = constant_script.GREATER_THAN, .TokenType = TokenType.GreaterThan },
    TokenPair{ .lexem = constant_script.LESS_THAN, .TokenType = TokenType.LessThan },
    TokenPair{ .lexem = constant_script.EQUALS_EQUALS, .TokenType = TokenType.EqualsEquals },
    TokenPair{ .lexem = constant_script.GREATER_THAN_EQUALS, .TokenType = TokenType.GreaterThanEquals },
    TokenPair{ .lexem = constant_script.LESS_THAN_EQUALS, .TokenType = TokenType.LessThanEquals },
    TokenPair{ .lexem = constant_script.MODULUS, .TokenType = TokenType.Modulus },
    TokenPair{ .lexem = constant_script.COMMENT, .TokenType = TokenType.Comment },
    TokenPair{ .lexem = constant_script.NOT_EQUALS, .TokenType = TokenType.NotEquals },
    TokenPair{ .lexem = constant_script.AND, .TokenType = TokenType.And },
    TokenPair{ .lexem = constant_script.AND_AND, .TokenType = TokenType.AndAnd },
    TokenPair{ .lexem = constant_script.OR, .TokenType = TokenType.Or },
    TokenPair{ .lexem = constant_script.OR_OR, .TokenType = TokenType.OrOr },
    TokenPair{ .lexem = constant_script.MODULUS_EQUALS, .TokenType = TokenType.ModulusEquals },

    TokenPair{ .lexem = constant_script.LEFT_PARENTHESIS, .TokenType = TokenType.LeftParenthesis },
    TokenPair{ .lexem = constant_script.RIGHT_PARENTHESIS, .TokenType = TokenType.RightParenthesis },
    TokenPair{ .lexem = constant_script.LEFT_BRACE, .TokenType = TokenType.LeftBrace },
    TokenPair{ .lexem = constant_script.RIGHT_BRACE, .TokenType = TokenType.RightBrace },
    TokenPair{ .lexem = constant_script.LEFT_SQUARE_BRACKET, .TokenType = TokenType.LeftSquareBracket },
    TokenPair{ .lexem = constant_script.RIGHT_SQUARE_BRACKET, .TokenType = TokenType.RightSquareBracket },
    TokenPair{ .lexem = constant_script.SEMICOLON, .TokenType = TokenType.Semicolon },
    TokenPair{ .lexem = constant_script.COMMA, .TokenType = TokenType.Comma },
    TokenPair{ .lexem = constant_script.FULL_STOP, .TokenType = TokenType.FullStop },
};
